create table "public"."Todos" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "completed" boolean not null default false,
    "name" text
);


alter table "public"."Todos" enable row level security;

CREATE UNIQUE INDEX "Todos_pkey" ON public."Todos" USING btree (id);

alter table "public"."Todos" add constraint "Todos_pkey" PRIMARY KEY using index "Todos_pkey";

create policy "Enable read access for all users"
on "public"."Todos"
as permissive
for all
to public
using (true);



set check_function_bodies = off;

CREATE OR REPLACE FUNCTION storage.can_insert_object(bucketid text, name text, owner uuid, metadata jsonb)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
BEGIN
  INSERT INTO "storage"."objects" ("bucket_id", "name", "owner", "metadata") VALUES (bucketid, name, owner, metadata);
  -- hack to rollback the successful insert
  RAISE sqlstate 'PT200' using
  message = 'ROLLBACK',
  detail = 'rollback successful insert';
END
$function$
;


